version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DOCKER=yes

  # chrome:
  #     #image: selenium/standalone-chrome:latest
  #     shm_size: 2gb
  #     container_name: selenium-chrome
  #     environment:
  #       - SE_NODE_MAX_SESSIONS=5
  #       - SE_NODE_SESSION_TIMEOUT=30
  #       - SE_VNC_NO_PASSWORD=1
  #       - SE_NODE_MAX_SESSIONS=2
  #     restart: always
  #     ports:
  #       - "4444:4444"